### ISSUE TITLE
[Feature Request] asyncio support

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [Vinyzu/chrome-fingerprints#1]
- [ ] read blocking without using a thread for sync
- [ ] use threading for asyncio read (or a async lzma library, for example https://aiomisc.readthedocs.io/en/latest/io.html#in-the-fly-compression)
- [ ] add example for asyncio to Readme

example script for running sync code in a thread with asyncio:
```python
loop = asyncio.get_event_loop()
await loop.run_in_executor(None, self.initialize_fingerprints)
```

see https://github.com/Vinyzu/chrome-fingerprints/blob/31be67c568d3f650535bb5f335015540d0872aea/chrome_fingerprints/fingerprints.py#L20-L32

**Comment by Vinyzu** [comment]
Resolved in [Add Async Support | Commit#7](https://github.com/Vinyzu/chrome-fingerprints/commit/a816d10ba75f56a3b3c897e188388e87931c2a68). Added as Co-Author, thank you for your work.
